#:schema node_modules/wrangler/config-schema.json
name = "superbasedd-actions"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
routes = [
    { pattern = "superbasedd.dial.to", custom_domain = true }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "superbasedd"
database_id = "164244ff-c6d1-4c8e-8fa4-4309d71e40e2"
